version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    networks:
      - go-network
    volumes:
      - mysql-data:/var/lib/mysql

  go-app:
    build: .
    container_name: tasks-api
    ports:
      - '8080:8080'
    environment:
      DB_HOST: ${DB_HOST_DOCKER}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - mysql
    networks:
      - go-network

volumes:
  mysql-data:

networks:
  go-network:
    driver: bridge
